gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_0"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_1"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_2"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_3"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_4"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_5"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_6"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_7"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_8"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_9"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_10"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_11"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_12"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_13"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_14"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_15"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_16"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_17"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_18"' --reptype gz.msgs.Boolean &
gz service -s /world/map/remove --reqtype gz.msgs.Entity --req 'type: MODEL; name: "target_19"' --reptype gz.msgs.Boolean &